"""Public package surface for libtestvim."""

from __future__ import annotations

from libtestvim.harness import VimHarness
from libtestvim.mcp_server import build_mcp_server, run_mcp_server
from libtestvim.models import (
    ArtifactBundle,
    BenchmarkReport,
    BenchmarkScenarioResult,
    CapabilityReport,
    CommandResult,
    CompareReport,
    CompareScenarioDelta,
    EnvironmentReport,
    GitRepoState,
    HistoryEntry,
    MultiCompareReport,
    PluginInfo,
    ProfileEntry,
    ProfileReport,
    RunResult,
    RunTelemetry,
    ScriptInfoEntry,
    ScriptInfoReport,
    StartupProfile,
    StartuptimeEvent,
    SuiteCollectionResult,
    SuiteResult,
    TmuxRunResult,
    ToolVersion,
)
from libtestvim.serde import (
    from_json,
    from_python,
    json_schema,
    to_json,
    to_json_bytes,
    to_jsonl,
)
from libtestvim.specs import (
    BenchmarkScenarioSpec,
    BenchmarkSpec,
    CompareSpec,
    HarnessSpec,
    InvocationSpec,
    TelemetrySpec,
)

__all__ = [
    "ArtifactBundle",
    "BenchmarkReport",
    "BenchmarkScenarioResult",
    "BenchmarkScenarioSpec",
    "BenchmarkSpec",
    "CapabilityReport",
    "CommandResult",
    "CompareReport",
    "CompareScenarioDelta",
    "CompareSpec",
    "EnvironmentReport",
    "GitRepoState",
    "HarnessSpec",
    "HistoryEntry",
    "InvocationSpec",
    "MultiCompareReport",
    "PluginInfo",
    "ProfileEntry",
    "ProfileReport",
    "RunResult",
    "RunTelemetry",
    "ScriptInfoEntry",
    "ScriptInfoReport",
    "StartupProfile",
    "StartuptimeEvent",
    "SuiteCollectionResult",
    "SuiteResult",
    "TelemetrySpec",
    "TmuxRunResult",
    "ToolVersion",
    "VimHarness",
    "build_mcp_server",
    "from_json",
    "from_python",
    "json_schema",
    "run_mcp_server",
    "to_json",
    "to_json_bytes",
    "to_jsonl",
]
